platform :ios, '8.0'
use_frameworks!

target 'cheongsam' do
    pod 'AFNetworking'
    pod 'SDCycleScrollView'
    pod 'Masonry'
    pod 'SDAutoLayout'
    pod 'MBProgressHUD'
    pod 'MJRefresh'
    pod 'WMPageController'
    pod 'SDWebImage'
    pod 'HMSegmentedControl'
    pod 'DZNEmptyDataSet'
    pod 'NJKWebViewProgress'
    pod 'FlatUIKit'
    pod 'RETableViewManager', '~> 1.6'
    pod 'JHUD'
    pod 'MJExtension'
    pod 'ReactiveCocoa', '2.5'
end

